import os
import re
from pathlib import Path

def extract_frontmatter(file_path):
    name = None
    description = None
    
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
            
        # Match frontmatter block
        match = re.search(r"^---\s*\n(.*?)\n---", content, re.DOTALL | re.MULTILINE)
        if match:
            fm_text = match.group(1)
            name_match = re.search(r"name:\s*(.+)", fm_text)
            desc_match = re.search(r"description:\s*(.+)", fm_text)
            
            if name_match:
                name = name_match.group(1).strip().strip("'\"")
            if desc_match:
                description = desc_match.group(1).strip().strip("'\"")
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
        
    return name, description

def generate_catalog():
    repo_dir = Path(os.path.dirname(os.path.abspath(__file__)))
    skills_dir = repo_dir / "skills"
    
    if not skills_dir.exists():
        print("Error: skills/ directory not found.")
        return

    skills_data = []
    
    for skill_folder in os.listdir(skills_dir):
        skill_path = skills_dir / skill_folder
        if not skill_path.is_dir():
            continue
            
        skill_md = skill_path / "SKILL.md"
        if skill_md.exists():
            name, desc = extract_frontmatter(skill_md)
            if not name:
                name = skill_folder
            if not desc:
                desc = "No description provided."
            skills_data.append((name, desc, skill_folder))
            
    # Sort alphabetically by skill name
    skills_data.sort(key=lambda x: x[0].lower())
    
    # Generate CATALOG.md
    catalog_path = repo_dir / "CATALOG.md"
    
    md_content = "# 📚 Enterprise Skill Catalog\n\n"
    md_content += f"> This catalog contains the **{len(skills_data)}** active and validated skills in the ecosystem.\n\n"
    
    md_content += "This catalog is automatically generated. Do not edit this file directly. Instead, modify the `SKILL.md` frontmatter of the respective skill and run `python generate_catalog.py`.\n\n"
    
    md_content += "| Skill Name | Description | Link |\n"
    md_content += "| :--- | :--- | :--- |\n"
    
    for name, desc, folder in skills_data:
        md_content += f"| **{name}** | {desc} | [View](skills/{folder}/SKILL.md) |\n"
        
    with open(catalog_path, "w", encoding="utf-8") as f:
        f.write(md_content)
        
    print(f"Successfully generated CATALOG.md with {len(skills_data)} skills.")

if __name__ == "__main__":
    generate_catalog()
